
name: CI Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose environment variables

      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> .env
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
        echo "DEBUG=False" >> .env # Set DEBUG to False for CI/CD environment

    - name: Build Docker Compose services
    
      run: docker compose build --no-deps --force-rm

    - name: Run tests (Placeholder - Implement your actual test suite)
     
      run: echo "No tests implemented yet. Add your test commands here!"

    - name: Clean up Docker resources
    
      run: docker compose down -v